### ISSUE TITLE
Anfrage Integration in ioBroker

### ISSUE THREAD

**Issue by sigi2345** [SOBOS-GmbH/pegelalarm_public_pas_doc#2]
Hallo,

kann man meine Daten der App in ioBroker (VIS) einbinden?
Oder wie bekomme ich die commonid für meine Stationen?

`PegelAlarm Hochwasser-Warnung, HydroSOS
Jährlich - Standard
€ 19,99/Jahr
Wird am 15.06.2021 verlängert
Abonnent seit 15.06.2020`

![Screenshot (64)](https://user-images.githubusercontent.com/41079106/84706361-1eb1a780-af5d-11ea-9e66-36d6b1a58c04.png)

Sigi

**Comment by sobos-office** [comment]
Jetzt hab ichs. Danke für den Hinweis!

**Comment by sigi2345** [comment]
> Jetzt hab ichs. Danke für den Hinweis!

Bitte sehr.

**Comment by sobos-office** [comment]
👍
