### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by RainerB74** [SOBOS-GmbH/pegelalarm_public_pas_doc#3]
Hello, everyone,
I get the following error message every minute:
instance system.adapter.pegelalarm.0 already running with pid 21086
Where can this come from? There is no PID in the error message.
Thanks in advance.
Rainer

**Comment by jstrassmayr** [comment]
Hi @RainerB74 ,
I assume that you are contacting us because you are using our API in ioBroker. Is that correct?

**Comment by RainerB74** [comment]
Hi @jstrassmayr,
yes that is correct.

**Comment by jstrassmayr** [comment]
@RainerB74 : We do not give support for the adapter as we did not create it. We only provide the API that is used in the adapter. Please contact the creator of the adapter. Please write me which adapter you are using so I can respond accordingly to requests from other users as well.

**Comment by RainerB74** [comment]
I am using the adapter: pegelalarm

**Comment by jstrassmayr** [comment]
Thank you! All the best
