### ISSUE TITLE
Flow rate

### ISSUE THREAD

**Issue by DonFabrizio** [SOBOS-GmbH/pegelalarm_public_pas_doc#4]
Hello, I am a river surfer. So for me it would be very interesting, if this adapter could also show the current flow rate. Many rivers are dammed, so the height does not say that much about the flow situation. Nonetheless really nice adapter!

**Comment by jstrassmayr** [comment]
The flow rate is only available for some rivers/stations.
Which river station(s) are you specifically interested in?

**Comment by DonFabrizio** [comment]
I would be interested in:
Germany Plochingen Neckar
Germany Plochingen Fils
Pegelalarm shows the flow rate for both.

**Comment by jstrassmayr** [comment]
The flow rate is available in our database so you can query it through our API.
But you need an API-key to access our API.
Please contact me through office@sobos.at
