### ISSUE TITLE
API Status Codes wrong

### ISSUE THREAD

**Issue by zuehlke-losc** [SOBOS-GmbH/pegelalarm_public_pas_doc#5]
I am experiencing two cases of the API returning the wrong status code.

1. Response has Status Code 200, but in the body the Status Code is 401. Is this intentional?
**My request:**
GET https://api.pegelalarm.at/api/station/1.1/flow/24012203-de/history?granularity=raw&loadEndDate=12.02.2024T16:35:46%2B0200&loadStartDate=12.02.2024T14:35:46%2B0200
**Response**
![image](https://github.com/SOBOS-GmbH/pegelalarm_public_pas_doc/assets/97896434/d257c143-1d90-4f2b-9079-c5eb24b38283)

2. Response has Status Code 500, when an invalid CommonId is passed. I would expect 404.
**My request:** https://api.pegelalarm.at/api/station/1.1/flow/1234/history?granularity=raw&loadEndDate=12.02.2024T16:47:33%2B0200&loadStartDate=12.02.2024T14:47:33%2B0200 
**Response**
![image](https://github.com/SOBOS-GmbH/pegelalarm_public_pas_doc/assets/97896434/b4755cb2-f388-40d3-86ea-5a481612bcfd)

**Comment by jstrassmayr** [comment]
Hi Lorenzo,
thanks for contacting us. 

Q1) In order to use our API, you'll need an API-key. If you don't have one, you'll receive a code 401 with unauthorized.
If you need an API-key, please contact us office@sobos.at

Q2) True. The error message should be enhanced.

**Comment by zuehlke-losc** [comment]
Hi Johannes

Thank you for answering so quickly. Regarding the first question I was refering to the missmatch of status code of response and body. The status of the HTTP response is 200, but in the body it sais 401, which is a bit confusing.

**Comment by jstrassmayr** [comment]
Hi Lorenzo,
you are right, it is confusing. 
We are already planning to enhance the return codes and descriptions as we found other room for improvement as well.
