### ISSUE TITLE
Fehlende Objekte unter Station

### ISSUE THREAD

**Issue by mest2** [SOBOS-GmbH/pegelalarm_public_pas_doc#6]
Hallo,
seit einigen Tagen sind die Objekte verschwunden.
Ich hatte den Rhein in Speyer ausgewählt.
Nehme ich den gesamten Rhein bekomme ich 5 Stationen in den Objekten angezeigt.

Vielen Dank für eure Mühe
Markus

**Comment by jstrassmayr** [comment]
Ich sehe derzeit aktuelle Daten für Rhein/Speyer:
![image](https://github.com/user-attachments/assets/3cedd4ec-7de9-44ff-8504-d61187929d6a)
Siehe https://www.sobos.at/paw/chart.html?commonid=23700600-de

Schick mir bitte ein Email an strassmayr@pegelalarm.at mit den Requests, die du verwendest.

LG Johannes
